version: '3.8'

networks:
  my-contacts:
    driver: bridge 

services:
  # frontend:
  #   image: frontend:latest
  #   depends_on:
  #     - "api"
  #   build: 
  #     context: frontend/.
  #     dockerfile: Dockerfile
  #   ports: 
  #     - "4000:4000"
  db-migration:
    depends_on:
      - "postgres"
    build:
      context: Api/.
      dockerfile: Migration.Dockerfile
    environment:
      ConnectionStrings:DefaultConnection: "Host=postgres;Port=5432;Database=contactdb;username=root;password=root"
      ConnectionStrings:IdentityConnection: "host=postgres;port=5432;database=contactdb;username=root;password=root"
    networks:
      - my-contacts  

  api:
    image: api:latest
    restart: always
    depends_on:
      - "db-migration"
    #command: ["dotnet", "ef" ,"database", "update", "--startup-project", "WebApi.csproj", "-c", "IdentityContext"]    
    build:
      context: Api/.
      dockerfile: Dockerfile
    ports:
      - "8000:80" 
    environment:
      ConnectionStrings:DefaultConnection: "Host=postgres;Port=5432;Database=contactdb;username=root;password=root"
      ConnectionStrings:IdentityConnection: "host=postgres;port=5432;database=contactdb;username=root;password=root"
      SendGridSettings:EmailFrom: "singhknitin@hotmail.com"
      SendGridSettings:Key: ""
      SendGridSettings:DisplayName: "Nitin Singh"
    networks:
      - my-contacts  
  postgres:
    restart: always
    build:
      context: postgres/.
      dockerfile: Dockerfile
    environment:
      POSTGRES_MULTIPLE_DATABASES: contactdb,identitydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      
    volumes:
      #- dbdata1:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
      # - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "5432:5432"
    networks:
      - my-contacts  

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - my-contacts 
volumes:
  dbdata1: